Repository adeira/universe, pull requests merged in 2022-10, with the labels that each got.

#5106 Removed isBright and isDark functions
  src/css-colors/CHANGELOG.md
  src/css-colors/README.md
  src/css-colors/src/__tests__/isBright.test.js
  src/css-colors/src/__tests__/isDark.test.js
  src/css-colors/src/index.js
  src/css-colors/src/isBright.js
  src/css-colors/src/isDark.js
Labels: automerge, hacktoberfest-accepted

#5116 CSS Colors: fix changelog entry
  src/css-colors/CHANGELOG.md
Labels: automerge priority

#5127 Abacus: fix the latest Clippy warning
  src/abacus/server/src/arango/analyzer.rs
  src/abacus/server/src/arango/aql.rs
  src/abacus/server/src/arango/collection/options.rs
  src/abacus/server/src/arango/connection/options.rs
  src/abacus/server/src/arango/document/options.rs
  src/abacus/server/src/arango/pool.rs
  src/abacus/server/src/arango/transaction.rs
  src/abacus/server/src/arango/view.rs
  src/abacus/server/src/images/mod.rs
Labels: automerge

#5136 Icons: release version 2.1.0
  src/abacus-backoffice/package.json
  src/abacus-kochka/package.json
  src/icons/CHANGELOG.md
  src/icons/package.json
  src/sx-design-headless/package.json
  src/sx-design/package.json
  yarn.lock
Labels: automerge

#5207 CI: add `shellcheck`
  .github/workflows/shellcheck.yml
Labels: automerge

#5208 NPM Publisher: add `collectFilenames` test
  src/monorepo-npm-publisher/src/__tests__/collectFilenames.test.js
  src/monorepo-npm-publisher/src/collectFilenames.js
  src/monorepo-npm-publisher/src/index.js
Labels: automerge

#5231 Created a simple Storybook story for Meter component. Closes issue #5029
  src/sx-design/README.md
  src/sx-design/src/Meter/Meter.stories.js
Labels: hacktoberfest-accepted

#5232 SX Design: showcase more `Meter` component states in the story
  src/sx-design/src/Meter/Meter.stories.js
Labels: automerge
